Modification of readTree and writeTree methods to preserve node labels during conversion between 'phylo' and 'TreeMan' classes.
DomBennett/treeman pull request #8
Opened 2020-10-25 16:57 UTC by T-Heide

Please see descriptions in the commit messages for details.

2020-10-31 17:40 UTC, DomBennett requested changes
Wow, thanks for the contribution!

Please consider the following changes that I've suggested and I'll approve it.

2020-10-31 17:40 UTC, DomBennett commented on R/cnvrt-methods.R
> +    node_labeller <- function(nd) { return(NULL) } # no node labels
When I started the project, I chose camel-case for for function names. Not standard for most R projects now.

```suggestion
    nodeLabeller <- function(nd) { return(NULL) } # no node labels 
```

2020-10-31 17:40 UTC, DomBennett commented on R/cnvrt-methods.R
> +    node_labeller <- function(n) { print(n); n[['id']] } # writes node labels
```suggestion
    nodeLabeller <- function(n) { n[['id']] } # writes node labels 
```
I don't thinking printing is necessary.

2020-10-31 17:40 UTC, DomBennett commented on R/cnvrt-methods.R
> +  writeTree(from, file=temp_file, ndLabels = node_labeller)
```suggestion
  writeTree(from, file=temp_file, ndLabels = nodeLabeller)
```

2020-10-31 17:40 UTC, DomBennett commented on R/read-write-methods.R
> +  }
```suggestion
  } else {
      # if using internal node ids as ids, no need for special slot
      other[intnds] <- NA
  }
```
No need to have a special node slot if the same information is contained in the IDs themsevles. TreeMan objects are memory-heavy enough as it is.

2020-10-31 17:40 UTC, DomBennett commented on tests/testthat/test-rw-methods.R
> +  tree <- readTree(text=text, spcl_slt_nm='bootstrap',
Special slot name "bootstrap" should not be needed.

2020-10-31 17:40 UTC, DomBennett commented on tests/testthat/test-rw-methods.R
> +test_that('readTree([w/ malformed node labels]) works', {
Can "malformed" be "non-id"?

2020-10-31 17:40 UTC, DomBennett commented on tests/testthat/test-rw-methods.R
>    expect_that(tree['ntips'], equals(4))
Can you add this? Probably should have been there all along.
```suggestion
  expect_equal(tree['othr_slt_nms'], 'bootstrap')
  expect_true(all(c('0.9', '0.8') %in%
                    as.character(getNdsSlt(tree = tree, slt_nm = 'bootstrap',
                                           ids = tree['nds']))))
  expect_that(tree['ntips'], equals(4))
```

2020-10-31 17:40 UTC, DomBennett commented on R/cnvrt-methods.R
>  setAs(from="TreeMan", to="phylo", def=function(from, to) {
Can you add something along the lines of "will attempt to preserve internal node id labels" or similar to the @description sections of the conversion docs? Thanks.

2020-11-01 10:31 UTC, T-Heide commented on R/cnvrt-methods.R
> +    node_labeller <- function(n) { print(n); n[['id']] } # writes node labels
Definitely not ...

2020-11-01 11:13 UTC, T-Heide commented on tests/testthat/test-rw-methods.R
> +test_that('readTree([w/ malformed node labels]) works', {
I have split the test into 'readTree([w/ special node slot]) works' and 'readTree([w/ non-standard node labels])' now.

2020-11-01 11:21 UTC, T-Heide commented
That should resolve all the comments.

2020-11-01 16:02 UTC, merged

2020-11-01 16:02 UTC, DomBennett commented
Nice, thanks!

2020-11-01 16:02 UTC, DomBennett reviewed
Accepted!